### ISSUE TITLE
Does 'import' work?

### ISSUE THREAD

**Issue by mcascone** [vmware-archive/terraform-provider-vra7#29]
**versions**
Terraform v0.12.7
\+ provider.vra7 v0.4.1

**Describe the bug**
`terraform import` fails on authentication. It appears as if it is not sending the user name correctly.

**To Reproduce**
1. Module `module.MASTER.vra7_deployment.vra-chef` is instantiated and applied
2. Terraform command: `terraform import module.MASTER.vra7_deployment.vra-chef  5021936a-66c7-01d4-bb16-41ca96c3517b`
3. Error:
```
Error: Error: Unable to get auth token: vRealize API: [{Code:90135 Message:Unable to authenticate user  in tenant Engineering. SystemMessage:90135-Unable to authenticate user  in tenant Engineering.} {Code:400 Message: SystemMessage:}]

  on modules\vra-chef\main.tf line 5, in provider "vra7":
   5: provider "vra7" {
```

**Expected behavior**
Terraform imports the machine specified into the resource ID. I have never actually seen this happen so I'm not 100% sure what to expect.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
[vra-terraform.log](https://github.com/terraform-providers/terraform-provider-vra7/files/3576621/vra-terraform.log)

2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
[PowerShell_transcript.CHI-MAXCA-10-01.qB5pgV5r.20190904164316.txt](https://github.com/terraform-providers/terraform-provider-vra7/files/3576625/PowerShell_transcript.CHI-MAXCA-10-01.qB5pgV5r.20190904164316.txt)

3. crash.log(if any)

**Desktop (please complete the following information):**
Win10

**Additional context**

**Comment by Prativa20** [comment]
@mcascone Working on it. Will update soon

**Comment by Prativa20** [comment]
@mcascone Import functionality is now supported in the latest version, v1.0.0.
Refer to README for detail.
