### ISSUE TITLE
Building this provider fails accessing https://git.apache.org/thrift.git

### ISSUE THREAD

**Issue by GMZwinge** [vmware-archive/terraform-provider-vra7#31]
I was trying to build the master branch of this provider to try the changes from the pull request "Pull network info from NETWORK_LIST json in resourceview" (#30). It now fails at:
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in F:\Tools\TerraForm\_Providers\terraform-provider-vra7\build\pkg\mod\cache\vcs\83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Timed out
go: error loading module requirements
```
From https://status.apache.org/, it seems that the repo "git.apache.org is not available at this time" and according to the referred [blog](https://blogs.apache.org/infra/entry/subversion-to-git-service-git) may not be for some time.

It seems that thrift may now be available in other places like https://gitbox.apache.org/repos/asf/thrift.git or https://github.com/apache/thrift. I tried replacing in this repo all references to git.apache.org to one of those, but it still fails for the same reason. May be it's a dependency, but I don't know enough about this to figure out how to address this problem.

**Comment by markpeek** [comment]
I [fixed](https://github.com/vmware/terraform-provider-vra/commit/270d9b27930c8e7fe23c7da83287774e9ac8e886) this in our newer provider for vRA 8 via adding this line to go.mod:

```
replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999
```

**Comment by GMZwinge** [comment]
Thanks @markpeek. It does indeed fix the above error. I now get another error accessing howett.net/plist, but it seems to be because our IT blocks howett.net because it's in the Category "personal-sites-and-blogs". Is there a similar alternative for that?

**Comment by GMZwinge** [comment]
Here is the full error:
`go: howett.net/plist@v0.0.0-20181124034731-591f970eefbb: unrecognized import path "howett.net/plist" (https fetch: Get https://howett.net/plist?go-get=1: read tcp 10.199.71.235:49917->13.77.158.121:443: wsarecv: An existing connection was forcibly closed by the remote host.)`

**Comment by markpeek** [comment]
That same technique likely will not work for that issue. Haven't tried it but using the proxy in Go 1.13 likely could bypass that block. But read about the privacy concerns if you have any internal repos.

**Comment by GMZwinge** [comment]
@markpeek Thanks Mark. I'll just wait until there is an official release that includes #30.
