### ISSUE TITLE
Terraform refresh does not work as intended.

### ISSUE THREAD

**Issue by soumik612** [vmware-archive/terraform-provider-vra7#38]
vRA 7.x version
7.4
Terraform version
v0.12.13
terraform-provider-vra7 plugin version
provider.vra7 v0.5.0

**Describe the bug**
During deployment of VM resource, TF timesout (using default timeout value) although the VM request is still "IN PROGRESS" on VRA.
TF show output when TF timesout:

# vra7_deployment.Windows_machine_01[0]: (tainted)
resource "vra7_deployment" "Windows_machine_01" {
    businessgroup_name     = "CP_PROD_CF_OBO_01"
    catalog_item_id        = "3a8b1715-7917-4589-b934-9c444184a642"
    catalog_item_name      = "IAAS-W2012-R2-Standard-x64-CF"
    id                     = "ed158554-8395-4d5d-a39f-a7ca4c77662a"
    request_status         = "IN_PROGRESS"
    resource_configuration = {

Once the VM is deployed, I assumed that using terraform refresh, the state file would be updated with current status.
TF refresh output once VM is successfully deployed:
# vra7_deployment.Windows_machine_01[0]: (tainted)
resource "vra7_deployment" "Windows_machine_01" {
    businessgroup_name     = "CP_PROD_CF_OBO_01"
    catalog_item_id        = "3a8b1715-7917-4589-b934-9c444184a642"
    catalog_item_name      = "IAAS-W2012-R2-Standard-x64-CF"
    id                     = "ed158554-8395-4d5d-a39f-a7ca4c77662a"
    request_status         = "IN_PROGRESS"
    resource_configuration = {

Problem arises when I do a TF plan, since the VM is already deployed, TF should show that no changes are required.
However, I get a mesage that the "resource is tainted, so must be replaced"

![image](https://user-images.githubusercontent.com/35273569/69341303-9c346400-0c69-11ea-946a-a4daf74ad20c.png)

**Expected behavior**
The resource status should be updated after terraform refresh.

**Comment by Prativa20** [comment]
@soumik612 Created a PR as an enhancement that will take care of this
#41

Please provide your feedback

**Comment by Prativa20** [comment]
@soumik612 This is fixed in v1.0.0. Please refer to the README, examples and documentation to migrate to the latest version
