### ISSUE TITLE
Cannot pass array of values in element of deployment_configuration or resource_configuration

### ISSUE THREAD

**Issue by MaciejKaras** [vmware-archive/terraform-provider-vra7#45]
**vRA 7.x version**
7.6
**Terraform version**
0.12.19
**terraform-provider-vra7 plugin version**
0.5.0

**Describe the bug**
Cannot pass array of values in element of deployment_configuration or resource_configuration. Arrays of values are necessary for some fields, based on catalog item template, but they are available to send through vRA API. Maybe there is a way but documentation is not suggesting any usage of this case whatsoever. In provider code the element of list is specified as `schema.TypeString`:
```go
"deployment_configuration": {
	Type:     schema.TypeMap,
	Optional: true,
	Elem:     schema.TypeString,
},
"resource_configuration": {
	Type:     schema.TypeMap,
	Optional: true,
	Computed: true,
	Elem:     schema.TypeString,
}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Terraform config file:
```hcl
resource "vra7_deployment" "create_vnet" {

  catalog_item_name = "Network - Create vNet"

  resource_configuration = {
        "Network_-_Create_vNet.0" = null
        "Network_-_Create_vNet.alternativeWins" = ""
        "Network_-_Create_vNet.availableScopes" = ["10.0.0.0/24", "172.16.0.0/16"]
        "Network_-_Create_vNet.businessGroups" = ["1stbg"]
  }
}
```
2. `Terraform plan`
3. Validation Error

**Expected behaviour**
A array value should be possible to send. And if it is please provide with documentation.

**Logs**
```logs
2020/02/18 09:25:30 [TRACE] <root>: eval: *terraform.EvalValidateResource
2020/02/18 09:25:30 [ERROR] <root>: eval: *terraform.EvalValidateResource, err: Incorrect attribute value type: Inappropriate value for attribute "resource_configuration": element "Network_-_Create_vNet.businessGroups": string required.
2020/02/18 09:25:30 [ERROR] <root>: eval: *terraform.EvalSequence, err: Incorrect attribute value type: Inappropriate value for attribute "resource_configuration": element "Network_-_Create_vNet.businessGroups": string required.
[...]
2020/02/18 09:25:30 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: Incorrect attribute value type
```

**Desktop (please complete the following information):**
 - OS: Mac OS X

**Comment by sokoow** [comment]
@Prativa20 thanks for fixing https://github.com/terraform-providers/terraform-provider-vra7/issues/37 - is this also something you can potentally answer ? :)

**Comment by Prativa20** [comment]
@MaciejKaras Added the support in resource_configuration as well.
