### ISSUE TITLE
Provider 1.0.0 - Required to specify all values even if there's a default specified in the blueprint

### ISSUE THREAD

**Issue by hobovirtual** [vmware-archive/terraform-provider-vra7#60]
**vRA 7.x version**
vRealize Automation 7.6

**Terraform version**
v0.12.24

**terraform-provider-vra7 plugin version**
The terraform-provider-vra7 plugin version 1.0.0

**Describe the bug**
New behavior in the latest provider, when deploying a blueprint, we need to declare a bunch of new values that were previously optional.

Example, lease_days, before 1.0.0 we could just use the default value (which was the minimal value defined in the blueprint) and same thing for the cluster (instance number of a component)

**To Reproduce**
1. maint.tf content

```
provider "vra7" {
    username = var.vra_username
    password = var.vra_password
    tenant = var.vra_tenant
    host = var.vra_host
    insecure = true
}

resource "vra7_deployment" "deployment" {
  businessgroup_name = "dev"
  catalog_item_name = "dev vm"              
  reasons = "provide a reason"
  description = "provide a description"
  //lease_days = 2

  resource_configuration {
    component_name = "vm1"
    //cluster = 1

    //Please Provide the following information for the bootstrap node component
    configuration = {
      "custom.midname" = "BASE"
    }
  } 
}
```

2. Terraform command
terraform apply

3. Error
Error: The catalog item **qequest** failed with error vRealize API: [{Code:20117 Mes
sage:The data specified within the request is invalid. SystemMessage:The data sp
ecified within the request is invalid.} {Code:11002 Message:The value of the '_c
luster' field cannot be less than 1. SystemMessage:The value of the field with i
d _cluster cannot be less than 1.} {Code:11002 Message:The value of the '_leaseD
ays' field cannot be less than 2. SystemMessage:The value of the field with id _
leaseDays cannot be less than 2.} {Code:400 Message: SystemMessage:}]

  on main.tf line 9, in resource "vra7_deployment" "deployment":
   9: resource "vra7_deployment" "deployment" {

**Expected behavior**
Don't declare property value when default exist in the blueprint

**Desktop (please complete the following information):**
 - OS: Windows 2016 and CentOS 7

PS: typo highlighted in bold for the error message, i guess this sould mention request instead of qequest :D

**Comment by Prativa20** [comment]
@hobovirtual The issue is fixed. If no cluster value is provided in the config, it assumes the default value in the request template.
