### ISSUE TITLE
Drift in state file

### ISSUE THREAD

**Issue by sandeep444033** [vmware-archive/terraform-provider-vra7#85]
**vRA 7.x version**
vRA 7.6 HF 7
**Terraform version**
Terraform v0.12.26
**terraform-provider-vra7 plugin version**
provider.vra7 v1.0.1

**Describe the bug**

I am using vra-7 provider and I have built 11 VM's with Terraform via vRA.

I see all of the 11 VM's getting created via vRA but the state file have details of only 8 servers and this is random, sometimes if I build 15 servers I only have 4 servers details in my state file.

From what I can see in the trace log, output, and configuration, the failure appears to be in the contents of the API response on the read. Terraform appears to send the creation request with the appropriate value, and receives back a successful creation response. It then performs the read, which also appears to succeed, it just does not have the complete contents. 

I am able to get hold of the REST API endpoint this provider is using for the final read is documented here, showing that there are page and limit parameters:

https://code.vmware.com/apis/39/vrealize-automation#/catalog-service/%2Fapi%2Fconsumer%2Frequests%2F%7Bid%7D%2FresourceViews

I am able to get the API working and did a GET call via Postman and found the following,

I need to hit 3 pages to pull all of my 11 servers information

$ grep -i VirtualMachineName page1 | wc -l
5
$ grep -i VirtualMachineName page 2 | wc -l
2
$ grep -i VirtualMachineName page3 |wc -l
4

page -1+page -2+page -3 = 11 servers (total servers of my vRA deployment)

So from the above I need to traverse through 3 pages to get all of my 11 servers information but I feel terraform is only grabbing the info on first page of API, but not on all.

**To Reproduce**
Deploy VM's with software component attached to it. Hit the following API, to see if you have all of your servers.

curl --location --request GET 'https://<vRA FQDN>/catalog-service/api/consumer/requests/<resource-ID from your deployment>/resourceViews' \
--header 'Authorization: Bearer xxxx' \
--data-raw ''

**Expected behavior**
Would it be possible to allow Terraform to get ifo of all pages on the mentioned API?

**Screenshots**
N/A

**Logs**
N/A

**Desktop (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by Prativa20** [comment]
@sandeep444033  This is fixed in the latest version v2.0.0

**Comment by sandeep444033** [comment]
@Prativa20 

Post upgrading my provider version to 2.0, it broke in my outputs with the following error,

Error: Unsupported attribute

  on vra-deployment.tf line 252, in output "machine_Names":
 252:   value = "${vra7_deployment.myDeployment[*].resource_configuration[*].name}"

This object does not have an attribute named "name".

I have following in my outputs,

## output
output "machine_IPs" {
  value = "${vra7_deployment.myDeployment[*].resource_configuration[*].ip_address}"
}
output "machine_Names" {
  value = "${vra7_deployment.myDeployment[*].resource_configuration[*].name}"
}

In notes you mentioned,

// this has been renamed from resource_state to instances. resource_state was a map, but instances is a list
     // it is a list of all VMs in the above cluster. each element in an instance represents a VM and its properties

resource_state is renamed but resource_configuration is still valid right?

**Comment by Prativa20** [comment]
@sandeep444033 Yes, there is a schema change. `resource_configuration` is still valid. The computed attributed inside resource_configuration has been modified.

To access ip_address and name, you can modify it to

```
output "machine_IPs" {
value = "${vra7_deployment.myDeployment[*].resource_configuration[*].instances[*].ip_address}"
}
output "machine_Names" {
value = "${vra7_deployment.myDeployment[*].resource_configuration[*].instances[*].name}"
}
```

Each resource_configuration in state file maps with the one in the .tf file. `instances` is a list within resource_configuration and it is based on the cluster size that you provide in the .tf file. The default cluster size is 1 if you do not specify while requesting.

Let me know if it works.

Thanks,
Prativa
