### ISSUE TITLE
Vra7

### ISSUE THREAD

**Issue by kenvpt** [vmware-archive/terraform-provider-vra7#91]
Is this Vra7 provider accomodate On prem vra7? Or only vmware Cloud?

**Comment by markpeek** [comment]
This provider is for the on-premises vRA 7.x. For vRA Cloud or on-premises vRA 8.x you would use [this](https://github.com/vmware/terraform-provider-vra) provider.

**Comment by kenvpt** [comment]
how about for vra 7 on prem?

**Comment by markpeek** [comment]
You are currently commenting in an issue for the vRA 7 on-premises provider.

**Comment by kenvpt** [comment]
oh sorry. I misunderstood your email awhile ago.
Im having issues authenticating.

My credentials are correct so Im not sure what I am doing wrong.

**Comment by Prativa20** [comment]
@kenvpt Which provider do you want to use? vra7(on-prem) or vra8(on-prem/cloud)? And can you share your main.tf?

**Comment by kenvpt** [comment]
vra7 on prem

**Comment by Prativa20** [comment]
@kenvpt This is how your main.tf should look like https://github.com/vmware/terraform-provider-vra7/blob/master/example/simple/main.tf

Please share the vra-terraform.log file. This must have been generated in your terraform workspace, same location as your .tf file

**Comment by kenvpt** [comment]
[image: image.png]

**Comment by kenvpt** [comment]
yeah my main.tf is like that. I just have separate the provider.tf to
main.tf. the error when doing terraform apply is the authentication part

**Comment by Prativa20** [comment]
@kenvpt I will need to check the logs to find out what is wrong. Can you share the vra-terraform.log file?

**Comment by kenvpt** [comment]
On that picture, the vra-terraform.log file is there. It has 4 lines of logs

**Comment by Prativa20** [comment]
@kenvpt I just see the following text and there is no image attached or any download link as in the screenshot below.

Alternative way could be to copy the file content and paste it in the comments.

![image](https://user-images.githubusercontent.com/10183678/94590367-6b369f80-023b-11eb-9850-6a01ac31b54b.png)
