### ISSUE TITLE
Description not getting updated on deployments post 2.0 upgrade.

### ISSUE THREAD

**Issue by sandeep444033** [vmware-archive/terraform-provider-vra7#92]
**vRA 7.x version**
vRA 7.6 HF 7
**Terraform version**
Terraform v0.12.26
**terraform-provider-vra7 plugin version**
provider.vra7 v2.0.0

**Describe the bug**
Post 2.0 upgrade, descriptions field is not getting updated on deployemnt.

I have following resource definition

resource "vra7_deployment" "myDeployment" {
  wait_timeout = "180"
  count             = 1
  catalog_item_name = var.blueprintName
  businessgroup_name = var.businessGroupVRA
  description = var.jiraticket

 }
**To Reproduce**
Do a terraform apply by passing description variable.

**Expected behavior**
Terraform need to update description field on vRA deployment.

**Comment by Prativa20** [comment]
This has been fixed in the latest version v2.0.1

Thanks,
Prativa
