### ISSUE TITLE
Scale out/in not working due to drift in Terraform state file

### ISSUE THREAD

**Issue by sandeep444033** [vmware-archive/terraform-provider-vra7#95]
**vRA 7.x version**
vRA 7.6 HF 7
**Terraform version**
Terraform v0.12.18
**terraform-provider-vra7 plugin version**
provider.vra7 v2.0.1

**Describe the bug**

Following scenarios of scale out/in are not working as expected with the Terraform provider for VMware vRealize Automation 7 version 2.0.1 due to disparities between vRA state and Terraform state.

Scale out VM count
Scale in from original VM count
Scale in from scaled-out VM count
Reconfigure the scaled-up VMs (hot add CPU/memory)

**To Reproduce**
This is mainly happening due to scaled out VM details are not storing in the Terraform state.

**Expected behavior**
Scaled out VM details should in the Terraform state accurately.

**Comment by Prativa20** [comment]
@sandeep444033 This is a known issue. I will look into it and update early next week.

Thanks,
Prativa

**Comment by Prativa20** [comment]
@sandeep444033 The fix is now available in v3.0.0

Thanks,
Prativa
