### ISSUE TITLE
Issue terraform plan

### ISSUE THREAD

**Issue by daneebrand** [vmware-archive/terraform-provider-vra7#97]
**vRA 7.x version**
7.6
**Terraform version**
Terraform v0.13.5
**terraform-provider-vra7 plugin version**
The terraform-provider-vra7 plugin 2.0.1

**Describe the bug**
I am able to deploy VMs using the latest official provider. Once the VMS are deployed, if I run a TF plan, the provider shows that the "resource_configuration" options need to be changed.

**Expected behavior**
Since the configuration has not been modified, the provider should not try to modify the config.
This creates a confusion, if there are new resources that need to be deployed.

I read a comment that this bug was corrected, but I'm having the issued with last provider version.

**Comment by Prativa20** [comment]
@daneebrand Can you please share your main.tf file?

Thanks,
Prativa

**Comment by daneebrand** [comment]
@Prativa20 

--- resource.tf file:
resource "vra7_deployment" "this" {
count = 1
catalog_item_id = var.catalog_item_id
businessgroup_id = var.businessgroup_id
description = "TerraForm"
reasons = "this"
lease_days = "0"


deployment_configuration = {
_number_of_instances = 1
_deploymentName= "this"
deployment_property = "Team"
}

resource_configuration {
component_name = var.component
cluster = 1
configuration = {
.. REMOVED
}
}
resource_configuration {
component_name = "Linux"
cluster = 1
configuration = {
.. REMOVED
}
}
wait_timeout = 20
}

Thanks

**Comment by Prativa20** [comment]
@daneebrand this issue has been fixed in the latest version 3.0.0 of the provider.
Please upgrade and reopen the bug if the issue still exists.

Thanks,
Prativa
